import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";

// Root layout for the Next.js app router. This file is executed on the server
// when rendering pages, and it composes the top-level HTML. We also import
// a Google font wrapper used by the site and render a shared `Navbar`.

// Note: `next/font/google` returns objects we use to set CSS variables so the
// fonts are available to client-side components via className.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  // Basic metadata for the app — adjust for production
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // The `children` prop is the rendered page content. Keep layout markup
  // minimal and place global providers, navbars, or footers here.
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Shared site navigation — simple component in components/navbar.js */}
        <Navbar />
        {/* Render the current page's content */}
        {children}
      </body>
    </html>
  );
}
